version: "3.4"
services:
  base:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: enumc:base
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./packages/enum-converter-api/package.json:/usr/src/app/packages/enum-converter-api/package.json
      - ./packages/enum-converter-web/package.json:/usr/src/app/packages/enum-converter-web/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock:delegated
  api:
    image: enumc:base
    working_dir: /usr/src/app/packages/enum-converter-api
    command: "yarn dev"
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes_from:
      - base
    volumes:
      - ./packages/enum-converter-api/tsconfig.json:/usr/src/app/packages/enum-converter-api/tsconfig.json
      - ./packages/enum-converter-api/package.json:/usr/src/app/packages/enum-converter-api/package.json
      - ./packages/enum-converter-api/src:/usr/src/app/packages/enum-converter-api/src
      - ./packages/enum-converter-api/build:/usr/src/app/packages/enum-converter-api/build
  web:
    image: enumc:base
    working_dir: /usr/src/app/packages/enum-converter-web
    command: "yarn dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "yarn workspace enum-converter-web dev"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes_from:
      - base
    volumes:
      - ./packages/enum-converter-web/src:/usr/src/app/packages/enum-converter-web/src
      - ./packages/enum-converter-web/public:/usr/src/app/packages/enum-converter-web/public

